task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('create/', views.LabelCreateView.as_view(), name='created'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail')
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from task_manager.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    ]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    first_name = models.CharField(
        max_length=150,
        blank=False,
        verbose_name=_('First Name')
    )
    last_name = models.CharField(
        max_length=150,
        blank=False,
        verbose_name=_('Last Name')
    )
    USERNAME_FIELD = 'username'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

task_manager/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        bs_cls = 'form-control bg-secondary bg-opacity-50 border-secondary'
        for field in self.fields.values():
            field.widget.attrs['class'] = bs_cls
            field.widget.attrs['placeholder'] = field.label

task_manager/labels/forms.py
from django.forms import ModelForm

from task_manager.labels.models import Labels
from task_manager.mixins import FormStyleMixin


class LabelCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Labels
        fields = ['name']

task_manager/statuses/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.statuses.models import Status


class StatusCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Status
        fields = ['name']

task_manager/tasks/forms.py
from django.forms import ModelForm

from task_manager.mixins import FormStyleMixin
from task_manager.tasks.models import Task


class TaskCreationForm(FormStyleMixin, ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from task_manager.mixins import FormStyleMixin
from task_manager.users.models import User


class BaseUserForm:
    """Base Meta settings for User forms."""
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username')
        help_texts = {
            'username': _(
                'Required. 150 characters or fewer. '
                'Letters, digits and @/./+/-/_ only.'
            ),
        }


class CustomUserCreationForm(FormStyleMixin, UserCreationForm):
    """User registration form with Bootstrap and password fields."""
    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')
        help_texts = {
            **BaseUserForm.Meta.help_texts,
            'password1':
                _('Your password must contain at least 3 characters.'),
            'password2':
                _('Please enter your password again to confirm.'),
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(
                _('A user with that username already exists.')
            )
        return username

    def clean(self):
        """Ensure passwords match and meet requirements."""
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error(
                    "password2",
                    _("Passwords don't match.")
                )

            if len(password1) < 3:
                self.add_error(
                    "password2",
                    _(
                        "This password is too short. "
                        "It must contain at least 3 characters."
                    ),
                )
        return cleaned_data


class CustomUserChangeForm(FormStyleMixin, forms.ModelForm):
    """User update form with password change and Bootstrap styling."""
    password1 = forms.CharField(
        label=_("New Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_("Your password must contain at least 3 characters."),
    )
    password2 = forms.CharField(
        label=_("Confirm Password"),
        widget=forms.PasswordInput,
        required=True,
        help_text=_("Please enter your password again to confirm."),
    )

    class Meta(BaseUserForm.Meta):
        fields = (*BaseUserForm.Meta.fields, 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            del self.fields['password']

    def clean(self):
        """Ensure passwords match."""
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error(
                    "password2",
                    _("Passwords don't match.")
                )
            elif len(password1) < 3:
                self.add_error(
                    "password2",
                    _(
                        "This password is too short. "
                        "It must contain at least 3 characters."
                    ),
                )
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        if password1 := self.cleaned_data.get("password1"):
            user.set_password(password1)
        if commit:
            user.save()
        return user

task_manager/labels/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.labels.forms import LabelCreationForm
from task_manager.labels.models import Labels
from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
)

URL_INDEX = 'labels:index'


class LabelListView(CustomLoginRequiredMixin, ListView):
    model = Labels
    template_name = 'labels/labels.html'
    context_object_name = 'labels'
    ordering = ['id']


class LabelCreateView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      CreateView):
    model = Labels
    template_name = 'labels/created.html'
    form_class = LabelCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was created successfully')
    extra_context = {
        'title': _('Create label'),
        'button_name': _('Create')
    }


class LabelUpdateView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      UpdateView):
    form_class = LabelCreationForm
    model = Labels
    template_name = 'labels/update.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was updated successfully')
    extra_context = {
        'title': _('Update label'),
        'button_name': _('Update')
    }


class LabelDeleteView(CustomLoginRequiredMixin,
                      SuccessMessageMixin,
                      ProtectErrorMixin,
                      DeleteView):
    template_name = 'labels/delete.html'
    model = Labels
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Label was deleted successfully')
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this label because they are being used'
    )
    extra_context = {
        'title': _('Label deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/statuses/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
)
from task_manager.statuses.forms import StatusCreationForm
from task_manager.statuses.models import Status

URL_INDEX = 'statuses:index'


class StatusListView(CustomLoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/status.html'
    context_object_name = 'statuses'
    ordering = ['id']


class StatusCreateView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       CreateView):
    model = Status
    template_name = 'statuses/created.html'
    form_class = StatusCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was created successfully')
    extra_context = {
        'title': _('Create status'),
        'button_name': _('Create')
    }


class StatusUpdateView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       UpdateView):
    form_class = StatusCreationForm
    model = Status
    template_name = 'statuses/update.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was updated successfully')
    extra_context = {
        'title': _('Update status'),
        'button_name': _('Update')
    }


class StatusDeleteView(CustomLoginRequiredMixin,
                       SuccessMessageMixin,
                       ProtectErrorMixin,
                       DeleteView):
    template_name = 'statuses/delete.html'
    model = Status
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Status was deleted successfully')
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this status because they are being used'
    )
    extra_context = {
        'title': _('Status deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.mixins import AuthorPermissionMixin, CustomLoginRequiredMixin
from task_manager.tasks.filters import TaskFilter
from task_manager.tasks.forms import TaskCreationForm
from task_manager.tasks.models import Task

URL_INDEX = 'tasks:index'


class TaskListView(CustomLoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/tasks.html'
    filterset_class = TaskFilter
    context_object_name = 'tasks'
    ordering = 'id'


class TaskDetailView(CustomLoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail_view.html'
    context_object_name = 'task'


class TaskCreateView(CustomLoginRequiredMixin,
                     SuccessMessageMixin,
                     CreateView):
    model = Task
    template_name = 'tasks/create.html'
    form_class = TaskCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was created successfully')
    extra_context = {
        'title': _('Create task'),
        'button_name': _('Create')
    }

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(CustomLoginRequiredMixin,
                     SuccessMessageMixin,
                     UpdateView):
    model = Task
    template_name = 'tasks/update.html'
    form_class = TaskCreationForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was updated successfully')
    extra_context = {
        'button_name': _('Update'),
        'title': _('Update task')
    }


class TaskDeleteView(CustomLoginRequiredMixin,
                     AuthorPermissionMixin,
                     SuccessMessageMixin,
                     DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('Task was deleted successfully')
    permission_denied_url = reverse_lazy(URL_INDEX)
    permission_denied_message = _("Only the task's author can delete it")
    extra_context = {
        'title': _('Task deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    CustomLoginRequiredMixin,
    ProtectErrorMixin,
    UserPermissionMixin,
)
from task_manager.users.forms import (
    CustomUserChangeForm,
    CustomUserCreationForm,
)
from task_manager.users.models import User

URL_INDEX = 'users:index'
ERROR_MESSAGE_NO_RIGHTS = _("You don't have rights to change another user.")


class UserListView(ListView):
    model = User
    template_name = 'users/users_list.html'
    context_object_name = 'users'
    ordering = ['id']


class BaseUserView(SuccessMessageMixin):
    model = User
    template_name = 'users/create.html'
    context_object_name = 'user'
    permission_denied_url = reverse_lazy('users:index')


class UserCreateView(BaseUserView, CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    success_message = _('User was registered successfully')
    extra_context = {
        'title': _('Sign Up'),
        'button_name': _('Register')
    }


class UserUpdateView(CustomLoginRequiredMixin, UserPermissionMixin,
                     BaseUserView, UpdateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('User was updated successfully')
    permission_denied_message = ERROR_MESSAGE_NO_RIGHTS
    template_name = 'users/update_user.html'
    extra_context = {
        'title': _('Edit profile'),
        'button_name': _('Save changes')
    }


class UserDeleteView(CustomLoginRequiredMixin, UserPermissionMixin,
                     ProtectErrorMixin, BaseUserView, DeleteView):
    template_name = 'users/delete_user.html'
    success_url = reverse_lazy(URL_INDEX)
    success_message = _('User was deleted successfully')
    permission_denied_message = ERROR_MESSAGE_NO_RIGHTS
    access_denied_message = ERROR_MESSAGE_NO_RIGHTS
    protected_object_url = reverse_lazy(URL_INDEX)
    protected_object_message = _(
        'Cannot delete this user because they are being used'
    )
    extra_context = {
        'title': _('User deletion'),
        'button_name': _('Yes, delete')
    }

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from task_manager.forms import CustomLoginForm


class CustomLoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/login.html'
    form_class = CustomLoginForm
    next_page = reverse_lazy('index')
    success_message = _('You were logged in')


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, _('You were logged out'))
        return super().dispatch(request, *args, **kwargs)

task_manager/templates/users/create.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="card shadow-lg rounded-4">
        <div class="card-body p-4">
          <h2 class="text-center mb-4">Регистрация</h2>

          <form method="post" novalidate>
            {% csrf_token %}

            {% if form.non_field_errors %}
              <div class="alert alert-danger">
                {% for error in form.non_field_errors %}
                  <div>{{ error }}</div>
                {% endfor %}
              </div>
            {% endif %}

            {% for field in form %}
              <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>

                {{ field }}

                {% for error in field.errors %}
                  <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}

                {% if field.help_text %}
                  <div class="form-text text-muted">{{ field.help_text }}</div>
                {% endif %}
              </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary w-100">Зарегистрировать</button>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/users/delete_user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

<style>
  #id_username, #id_email, #id_first_name, #id_last_name {
    width: 100% !important;
  }
</style>
{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="card shadow-lg rounded-4">
        <div class="card-body p-4">
          <h2 class="text-center mb-4">Удаление пользователя</h2>
          <p class="text-center text-muted mb-4">Вы уверены, что хотите удалить пользователя <strong>{{ object.username }}</strong>?</p>
          <form method="post">
            {% csrf_token %}
            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-danger">Да, удалить</button>
              <a href="{% url 'users:index' %}" class="btn btn-primary w-100">Отмена</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/users/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<style>
  #id_username, #id_password {
    width: 100% !important;
  }
</style>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-5">
      <div class="card shadow-lg rounded-4">
        <div class="card-body p-4">
          <h2 class="text-center mb-4">Вход</h2>

          <form method="post">
            {% csrf_token %}

            <div class="mb-3">
              <label for="{{ form.username.id_for_label }}" class="form-label">
                {{ form.username.label }}
              </label>
              {{ form.username }}
              {% if form.username.errors %}
                <div class="text-danger">
                  {{ form.username.errors }}
                </div>
              {% endif %}
            </div>

            <div class="mb-3">
              <label for="{{ form.password.id_for_label }}" class="form-label">
                {{ form.password.label }}
              </label>
              {{ form.password }}
              {% if form.password.errors %}
                <div class="text-danger">
                  {{ form.password.errors }}
                </div>
              {% endif %}
            </div>

            {% if form.non_field_errors %}
              <div class="alert alert-danger">
                {{ form.non_field_errors }}
              </div>
            {% endif %}

            <button type="submit" class="btn btn-primary w-100">Войти</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/users/update_user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow-lg rounded-4">
        <div class="card-body p-4">
          <h2 class="text-center mb-4">Редактирование профиля</h2>

          <form method="post">
            {% csrf_token %}

            {% if form.non_field_errors %}
              <div class="alert alert-danger">
                {{ form.non_field_errors }}
              </div>
            {% endif %}

            {% for field in form %}
              <div class="mb-3">
                <label for="{{ field.id_for_label }}" class="form-label">
                  {{ field.label }}
                </label>
                {{ field }}
                {% if field.errors %}
                  <div class="text-danger">
                    {{ field.errors }}
                  </div>
                {% endif %}
              </div>
            {% endfor %}

            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary">Изменить</button>
              <a href="{% url 'index' %}" class="btn btn-outline-secondary">Отмена</a>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

task_manager/templates/users/users_list.html
{% extends "base.html" %}

{% block content %}

{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
  {% endfor %}
{% endif %}

<h1>Пользователи</h1>

<table class="table table-striped">
    <thead>
    <tr>
    <th>id</th>
    <th>Имя пользователя</th>
    <th>Полное имя</th>
    <th>Дата создания</th>
    <th>Действие</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
    <tr>
      <td>{{ user.id }}</td>
      <td>{{ user.username }}</td>
      <td>{{ user.first_name }} {{ user.last_name }}</td>
      <td>{{ user.date_joined|date:"d.m.Y" }}</td>
        <td class=''>
            {% if user.in_use %}
            <button class="btn btn-primary" disabled title="Невозможно удалить, пользователь в использовании">Удалить</button>
           {% else %}
            <a class="btn btn-primary" href="{% url 'users:delete' user.pk %}">Удалить</a>
           {% endif %}
            <a class="btn btn-primary" href="{% url 'users:update' user.id %}" role="button">Изменить</a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}